const crop = [
  {
    id: "w1",
    category: "wood",
    title: "محصول 1",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w2",
    category: "wood",
    title: "محصول 2",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w3",
    category: "wood",
    title: "محصول 3",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w4",
    category: "wood",
    title: "محصول 4",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w5",
    category: "wood",
    title: "محصول 5",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w6",
    category: "wood",
    title: "محصول 6",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w7",
    category: "wood",
    title: "محصول 7",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "w8",
    category: "wood",
    title: "محصول 8",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },

  {
    id: "c1",
    category: "copper",
    title: "محصول 1",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c2",
    category: "copper",
    title: "محصول 2",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c3",
    category: "copper",
    title: "محصول 3",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c4",
    category: "copper",
    title: "محصول 4",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c5",
    category: "copper",
    title: "محصول 5",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c6",
    category: "copper",
    title: "محصول 6",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c7",
    category: "copper",
    title: "محصول 7",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "c8",
    category: "copper",
    title: "محصول 8",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },

  {
    id: "ca1",
    category: "carpet",
    title: "محصول 1",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca2",
    category: "carpet",
    title: "محصول 2",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca3",
    category: "carpet",
    title: "محصول 3",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca4",
    category: "carpet",
    title: "محصول 4",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca5",
    category: "carpet",
    title: "محصول 5",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca6",
    category: "carpet",
    title: "محصول 6",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca7",
    category: "coppet",
    title: "محصول 7",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "ca8",
    category: "carpet",
    title: "محصول 8",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },

  {
    id: "s1",
    category: "statue",
    title: "محصول 1",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s2",
    category: "statue",
    title: "محصول 2",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s3",
    category: "statue",
    title: "محصول 3",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s4",
    category: "copper",
    title: "محصول 4",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s5",
    category: "statue",
    title: "محصول 5",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s6",
    category: "statue",
    title: "محصول 6",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s7",
    category: "statue",
    title: "محصول 7",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
  {
    id: "s8",
    category: "statue",
    title: "محصول 8",
    Description: "توضیحات",
    price: 10000,
    image: "/images/download-4.webp",
  },
];

export default crop;
